# Generated by Django 3.2.6 on 2021-08-31 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth.hashers import make_password

def create_user(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    for aUser in ['user1', 'user2']:
        user = User(
            username=aUser,
            email=f'{aUser}@mail.com',
            password=make_password(aUser),
            is_superuser=False,
            is_staff=False
        )
        user.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_user),
    ]
